FROM golang:1.26-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY pkgs/ ./pkgs/
COPY internals/search/ ./internals/search/
COPY cmd/search/ ./cmd/search/

RUN CGO_ENABLED=0 GOOS=linux go build -o /app/build/main ./cmd/search/
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/build/worker ./cmd/search/worker/

FROM alpine:3.19
WORKDIR /app
COPY --from=builder /app/build/main .
EXPOSE 5003
CMD ["./main"]
