name: demo-app-api-dev
services:
  auth:
     image: quay.io/keycloak/keycloak:latest
     container_name: keycloak
     command: ["start-dev"]
     env_file:
       - ./envs/dev/auth/.env.docker
     ports:
       - '5000:8080'
  jaeger:
    image: cr.jaegertracing.io/jaegertracing/jaeger:latest
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
  redis:
    image: redis:8.6.0-alpine3.23
    command: "redis-server --requirepass 'root'"
    ports:
      - "6379:6379"
  kafka:
    image: apache/kafka:latest
    env_file:
      - ./envs/dev/kafka/.env.docker
    ports:
      - "9092:9092"
      - "29092:29092"
  kafbat-ui:
    container_name: kafbat-ui
    image: ghcr.io/kafbat/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: true
    volumes:
      - ./envs/dev/kafka/config/kafka-ui/kafbat-ui.yaml:/etc/kafkaui/dynamic_config.yaml

  product-db:
     image: postgres:18.1-alpine3.23
     env_file:
       - ./envs/dev/product/.env.docker
     ports:
        - "6432:5432"
