// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package product_postgresdb

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type OutboxMessage struct {
	ID          string             `json:"id"`
	EventType   string             `json:"event_type"`
	AggrID      string             `json:"aggr_id"`
	AggrVersion int32              `json:"aggr_version"`
	Status      string             `json:"status"`
	Payload     []byte             `json:"payload"`
	Metadata    []byte             `json:"metadata"`
	RetryCount  int32              `json:"retry_count"`
	NextRetryAt pgtype.Timestamptz `json:"next_retry_at"`
	ErrText     *string            `json:"err_text"`
	ConsumedAt  pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
	Version     *int32             `json:"version"`
}

type Product struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	ImageUrl    *string   `json:"image_url"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	Version     *int32    `json:"version"`
}
