// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package product_postgresdb

import (
	"context"
)

type Querier interface {
	CreateProduct(ctx context.Context, arg *CreateProductParams) (*Product, error)
}

var _ Querier = (*Queries)(nil)
