FROM golang:1.26-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY pkgs/ ./pkgs/
COPY internals/product/ ./internals/product/
COPY cmd/product/ ./cmd/product/

RUN CGO_ENABLED=0 GOOS=linux go build -o /app/build/main ./cmd/product/
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/build/worker ./cmd/product/worker/

FROM alpine:3.19
WORKDIR /app
COPY --from=builder /app/build/main .
EXPOSE 5002
CMD ["./main"]
